
services:
  api:
    build: .
    container_name: api-dog
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=senha123
      - DB_NAME=db_cao_comunitario
    depends_on:
      - mysql

          
    command: >
      sh -c "
        chmod +x /app/wait-for-it.sh &&
        /app/wait-for-it.sh mysql:3306 --timeout=30 --strict -- 
        sh -c 'npx sequelize-cli db:migrate && npm run dev'
      "
  mysql:
    image: mysql:8.0 
    container_name: mysql
    restart: always 
    ports:
      - "3306:3306"  
    environment:
      MYSQL_ROOT_PASSWORD: senha123 
      MYSQL_DATABASE: db_cao_comunitario 
  
